/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_estech_api_jni_NativeImageOps */

#ifndef _Included_org_estech_api_jni_NativeImageOps
#define _Included_org_estech_api_jni_NativeImageOps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_estech_api_jni_NativeImageOps
 * Method:    preprocessToCHWNative
 * Signature: (Ljava/nio/ByteBuffer;IIFFFFFF)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_estech_api_jni_NativeImageOps_preprocessToCHWNative
  (JNIEnv *, jclass, jobject, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_estech_api_jni_NativeImageOps
 * Method:    freeBufferNative
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_estech_api_jni_NativeImageOps_freeBufferNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
