/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_estech_api_jni_NativeImageOps */

#ifndef _Included_org_estech_api_jni_NativeImageOps
#define _Included_org_estech_api_jni_NativeImageOps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_estech_api_jni_NativeImageOps
 * Method:    preprocessToCHWNative
 * Signature: (Ljava/nio/ByteBuffer;IIFFFFFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_estech_api_jni_NativeImageOps_preprocessToCHWNative
  (JNIEnv *, jobject, jobject, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
